floorplan:
# Dimmer lights
  - name: DC_DIMMER_STATUS_3
    instance: 21
    type: dimmer_switch
    instance_name: Bath

  - name: DC_DIMMER_STATUS_3
    instance: 22
    type: dimmer_switch
    instance_name: Front ceiling

  - name: DC_DIMMER_STATUS_3
    instance: 24
    type: dimmer_switch
    instance_name: Galley

  - name: DC_DIMMER_STATUS_3
    instance: 25
    type: dimmer_switch
    instance_name: Slide

  - name: DC_DIMMER_STATUS_3
    instance: 26
    type: dimmer_switch
    instance_name: Accent

  - name: DC_DIMMER_STATUS_3
    instance: 29
    type: dimmer_switch
    instance_name: Awning

  - name: DC_DIMMER_STATUS_3
    instance: 32
    type: dimmer_switch
    instance_name: Porch

  - name: DC_DIMMER_STATUS_3
    instance: 34
    type: dimmer_switch
    instance_name: TV

# Binary lights
  - name: DC_DIMMER_STATUS_3
    instance: 30
    type: light_switch
    instance_name: Baggage

  - name: DC_DIMMER_STATUS_3
    instance: 31
    type: light_switch
    instance_name: Assist handle

  - name: DC_DIMMER_STATUS_3
    instance: 38
    type: light_switch
    instance_name: Reading

  - name: DC_DIMMER_STATUS_3
    instance: 39
    type: light_switch
    instance_name: Shower

# Tanks
  - name: TANK_STATUS
    instance: 3
    type: tank_level
    instance_name: Propane tank

  - name: TANK_STATUS
    instance: 2
    type: tank_level
    instance_name: Grey water tank

  - name: TANK_STATUS
    instance: 1
    type: tank_level
    instance_name: Black water tank

  - name: TANK_STATUS
    instance: 0
    type: tank_level
    instance_name: Freshwater tank

# Switches
  - name: DC_DIMMER_STATUS_3
    instance: 40
    type: power_switch
    instance_name: Starlink

  - name: DC_DIMMER_STATUS_3
    instance: 44
    type: power_switch
    instance_name: Water pump

# Fans
  - name: DC_DIMMER_STATUS_3
    instance: 4
    type: vent_lid
    instance_name: Galley fan up    #must contain up or down for fans
    link_id: galley-fan-up

  - name: DC_DIMMER_STATUS_3
    instance: 5
    type: vent_lid
    instance_name: Galley fan down  #must contain up or down for fans
    link_id: galley-fan-down

  - name: DC_DIMMER_STATUS_3
    instance: 3
    type: vent_fan                  #Parent fan entity must come after lids
    instance_name: Galley fan
    entity_links:
      - galley-fan-up
      - galley-fan-down

  - name: DC_DIMMER_STATUS_3
    instance: 7
    type: vent_lid
    instance_name: Bathroom fan up
    link_id: bathroom-fan-up

  - name: DC_DIMMER_STATUS_3
    instance: 8
    type: vent_lid
    instance_name: Bathroom fan down
    link_id: bathroom-fan-down

  - name: DC_DIMMER_STATUS_3
    instance: 6
    type: vent_fan
    instance_name: Bathroom fan
    entity_links:
      - bathroom-fan-up
      - bathroom-fan-down

# Water heater
  - name: WATERHEATER_STATUS
    instance: 200
    type: water_heater
    instance_name: Water heater

# HVAC
  - name: THERMOSTAT_AMBIENT_STATUS
    instance: 3
    type: temperature
    instance_name: Temperature
    link_id: temperature

  - name: THERMOSTAT_STATUS_1
    type: furnace_mode
    instance_name: Furnace mode
    instance: 2
    link_id: furnace-mode

  - name: THERMOSTAT_STATUS_1
    type: furnace_action
    instance_name: Furnace action
    instance: 200
    link_id: furnace-action

  - name: THERMOSTAT_STATUS_1
    type: hvac
    instance_name: Thermostat
    instance: 3
    entity_links:
      - temperature
      - furnace-mode
      - furnace-action

  - name: THERMOSTAT_STATUS_1
    type: test
    instance_name: Virtual AC
    instance: 3

  - name: THERMOSTAT_STATUS_1
    type: test
    instance_name: Aventa
    instance: 161

  - name: AIR_CONDITIONER_STATUS
    type: test2
    instance_name: Virtual AC2
    instance: 1

  - name: AIR_CONDITIONER_STATUS
    type: test2
    instance_name: Aventa2
    instance: 161