floorplan:
#Dimmer lights
  - name: DC_DIMMER_STATUS_3
    instance: 21
    type: dimmer_switch
    instance_name: Bath

  - name: DC_DIMMER_STATUS_3
    instance: 22
    type: dimmer_switch
    instance_name: Front ceiling

  - name: DC_DIMMER_STATUS_3
    instance: 24
    type: dimmer_switch
    instance_name: Galley

  - name: DC_DIMMER_STATUS_3
    instance: 25
    type: dimmer_switch
    instance_name: Slide

  - name: DC_DIMMER_STATUS_3
    instance: 26
    type: dimmer_switch
    instance_name: Accent

  - name: DC_DIMMER_STATUS_3
    instance: 29
    type: dimmer_switch
    instance_name: Awning

  - name: DC_DIMMER_STATUS_3
    instance: 32
    type: dimmer_switch
    instance_name: Porch

  - name: DC_DIMMER_STATUS_3
    instance: 34
    type: dimmer_switch
    instance_name: TV

#Binary lights
  - name: DC_DIMMER_STATUS_3
    instance: 30
    type: light_switch
    instance_name: Baggage

  - name: DC_DIMMER_STATUS_3
    instance: 31
    type: light_switch
    instance_name: Assist handle

  - name: DC_DIMMER_STATUS_3
    instance: 38
    type: light_switch
    instance_name: Reading

  - name: DC_DIMMER_STATUS_3
    instance: 39
    type: light_switch
    instance_name: Shower

#Tanks
  - name: TANK_STATUS
    instance: 3
    type: tank_level
    instance_name: Propane tank

  - name: TANK_STATUS
    instance: 2
    type: tank_level
    instance_name: Grey water tank

  - name: TANK_STATUS
    instance: 1
    type: tank_level
    instance_name: Black water tank

  - name: TANK_STATUS
    instance: 0
    type: tank_level
    instance_name: Freshwater tank

#Switches
  - name: DC_DIMMER_STATUS_3
    instance: 40
    type: power_switch
    instance_name: Starlink

  - name: DC_DIMMER_STATUS_3
    instance: 44
    type: power_switch
    instance_name: Water pump

#Fans
  - name: DC_DIMMER_STATUS_3
    instance: 3
    type: vent_fan
    instance_name: Galley fan

  - name: DC_DIMMER_STATUS_3
    instance: 6
    type: vent_fan
    instance_name: Bathroom fan